name: 'Usabl Duplicate Task GitHub Action'
description: 'Triggers a task or series of tasks to duplicate and run again in the Usabl app.'
author: 'Usabl'
branding:
  icon: toggle-right
  color: gray-dark
inputs:
  companyID: 
    description: 'The companyID found under Settings in the Usabl dashboard.'
    required: true
  tasksToCopy: 
    description: "TaskIDs to duplicate. Each taskID can be found on the Home page in the Usabl dashboard."
    required: true
  accessCode: 
    description: "Access code with write access to the Usabl project. Found on the Settings page in the Usabl dashboard"
    required: true
runs:
  using: 'node12'
  main: 'index.js'
  env:
    USABL_ACCESS_TOKEN: ${{ inputs.accessToken }}